### ISSUE TITLE
Take look at VulkanCore

### ISSUE THREAD

**Issue by amerkoleci** [mellinoe/vk#1]
Hi dude,
I think you should take look at: https://github.com/discosultan/VulkanCore
I'm using it for my game engine and supports .NET Standard.

Take look

**Comment by mellinoe** [comment]
Hey, thanks for the pointer. I'm aware that there are quite a few other bindings out there, most of which are much more full-featured than mine. I'm mostly doing this as a learning exercise and to force myself to understand things from the ground up. There's also a few things I'm planning on doing differently from those bindings:

* I don't believe it is valid to use PInvoke's for Vulkan functions, although it may happen to work in many cases. This is because:
  * Functions are [not guaranteed to be statically exported](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkGetInstanceProcAddr.html) by the Vulkan library on all platforms.
  * The Vulkan shared library does not have the same name on all platforms, and CoreCLR does not support any feature like Mono's dllmap, so the PInvoke declarations cannot be written portably. For example, it looks like VulkanCore has PInvokes which are all to `"vulkan-1.dll"`, which won't work outside of Windows on CoreCLR.
  * This is not a correctness problem, but I believe it will most likely be faster (less overhead per-call) to load the function pointers manually and use a `calli` pattern, similar to what SharpDX and OpenTK do.
* I would prefer to have a raw, strictly-unsafe layer that simply wraps the Vulkan functions and structures. I would prefer to implement disposability, lifetime handling, etc. in a higher level, like in a rendering engine.
* I think auto-generation is a better approach here for maintainability. I get that the documentation is a bit harder to maintain, but OpenTK/SharpDX both have pretty decent documentation which seems derived from the official stuff. So I think it's still doable, and in an automated fashion.

**Comment by mellinoe** [comment]
I'm happy to continue discussing this, but I'm going to close the issue.

**Comment by amerkoleci** [comment]
I see, will gladly follow your progress as in all engine stuff you're doing.

Keep up the good work :)
